/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import com.easynth.lookandfeel.EaSynthLookAndFeel;
import javax.swing.*;

/**
 *
 * @author Annie
 */
public class LookAndFeel extends javax.swing.JDialog {

    private static final String RUTA_LOGO1 = "/interfaz/imgs/paleta2.png";

    /**
     * Creates new form LookAndFeel
     */
    public LookAndFeel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource(RUTA_LOGO1)).getImage());
        //Cambiar apariencia (Look and Feel)
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();
        for (UIManager.LookAndFeelInfo lfi : UIManager.getInstalledLookAndFeels()) {
            dcm.addElement(lfi.getName());
        }
        jComboBoxLookAndFeel.setModel(dcm);//para que rellene el combo de todos los looksandfeels que hay disponibles en el sitema
        this.setLocationRelativeTo(null);
        setTitle("Look & Feel (Apariencia)");
        this.setSize(500, 220);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLook = new javax.swing.JPanel();
        jLabelSeleccionaDiseño = new javax.swing.JLabel();
        jComboBoxLookAndFeel = new javax.swing.JComboBox<>();
        jButtonAceptarLook = new javax.swing.JButton();
        jLabelLook = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelSeleccionaDiseño.setText(org.openide.util.NbBundle.getMessage(LookAndFeel.class, "LookAndFeel.jLabelSeleccionaDiseño.text")); // NOI18N

        jComboBoxLookAndFeel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLookAndFeelActionPerformed(evt);
            }
        });

        jButtonAceptarLook.setText(org.openide.util.NbBundle.getMessage(LookAndFeel.class, "LookAndFeel.jButtonAceptarLook.text")); // NOI18N
        jButtonAceptarLook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarLookActionPerformed(evt);
            }
        });

        jLabelLook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imgs/paleta.png"))); // NOI18N
        jLabelLook.setText(org.openide.util.NbBundle.getMessage(LookAndFeel.class, "LookAndFeel.jLabelLook.text")); // NOI18N

        javax.swing.GroupLayout jPanelLookLayout = new javax.swing.GroupLayout(jPanelLook);
        jPanelLook.setLayout(jPanelLookLayout);
        jPanelLookLayout.setHorizontalGroup(
            jPanelLookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSeleccionaDiseño, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLookLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelLook)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAceptarLook))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLookLayout.setVerticalGroup(
            jPanelLookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSeleccionaDiseño)
                .addGap(18, 18, 18)
                .addGroup(jPanelLookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLook)
                    .addGroup(jPanelLookLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jComboBoxLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAceptarLook)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Cambiar apariencia (Look and Feel)
     *
     * @param evt
     */
    private void jComboBoxLookAndFeelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLookAndFeelActionPerformed
        try {
            UIManager.setLookAndFeel(UIManager.getInstalledLookAndFeels()[jComboBoxLookAndFeel.getSelectedIndex()].getClassName());
            SwingUtilities.updateComponentTreeUI(this);//para que se carguen los laf en las demas pantallas
            SwingUtilities.updateComponentTreeUI(this.getParent());//Para que se carguen los laf en la pantalla principal

        } catch (Throwable e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error estableciendo Look And Feel");
        }
    }//GEN-LAST:event_jComboBoxLookAndFeelActionPerformed

    private void jButtonAceptarLookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarLookActionPerformed
        dispose();

    }//GEN-LAST:event_jButtonAceptarLookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptarLook;
    private javax.swing.JComboBox<String> jComboBoxLookAndFeel;
    private javax.swing.JLabel jLabelLook;
    private javax.swing.JLabel jLabelSeleccionaDiseño;
    private javax.swing.JPanel jPanelLook;
    // End of variables declaration//GEN-END:variables
}
